// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlcreuaesIUU_rOVry9PGHqToSeHM548k',
    appId: '1:263208865722:web:655c6c85508813b2f4d783',
    messagingSenderId: '263208865722',
    projectId: 'smart-home-69271',
    authDomain: 'smart-home-69271.firebaseapp.com',
    storageBucket: 'smart-home-69271.firebasestorage.app',
    measurementId: 'G-RGHCEE27X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3AwORqLWac3JpnfUydCxrMSt2CJNtqck',
    appId: '1:263208865722:android:6c50df6e18ab820df4d783',
    messagingSenderId: '263208865722',
    projectId: 'smart-home-69271',
    storageBucket: 'smart-home-69271.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfzmeJqFOifCZHNSXVuZTMEfoB9vo_Hso',
    appId: '1:263208865722:ios:e5136fd660c822fcf4d783',
    messagingSenderId: '263208865722',
    projectId: 'smart-home-69271',
    storageBucket: 'smart-home-69271.firebasestorage.app',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfzmeJqFOifCZHNSXVuZTMEfoB9vo_Hso',
    appId: '1:263208865722:ios:e5136fd660c822fcf4d783',
    messagingSenderId: '263208865722',
    projectId: 'smart-home-69271',
    storageBucket: 'smart-home-69271.firebasestorage.app',
    iosBundleId: 'com.example.smartHome',
  );
}
