name: Flutter CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create dummy .env file
        run: |
          touch .env
          echo "MQTT_BROKER_URL=broker.hivemq.com" > .env

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Run tests with coverage
        run: |
          flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: 3c8cb294-ea77-4cee-b38d-70dc5ba16182
          files: coverage/lcov.info
          fail_ci_if_error: true
