name: Flutter CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up flutter_matter dependency
        run: |
          sudo mkdir -p /home/dexter/flutter_library
          sudo chown -R $USER:$USER /home/dexter
          git clone https://github.com/abod8639/flutter_matter.git /home/dexter/flutter_library/flutter_matter

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Run tests with coverage
        run: |
          flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: 3c8cb294-ea77-4cee-b38d-70dc5ba16182
          files: coverage/lcov.info
          fail_ci_if_error: true
